name: asdf-java Tests
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macOS-latest']
    env:
      TERM: dumb
    steps:
    - uses: actions/checkout@v2
#    - uses: mstksg/get-package@v1
    - uses: delgurth/get-package@v3
      with:
        brew: bash coreutils jq shellcheck fish xonsh zsh
        apt-get: jq shellcheck zsh fish xonsh bash
    - name: Run ShellCheck
      run: |
        shellcheck -V
        shellcheck ./bin/functions
        shellcheck ./update_data.bash
    - name: Install asdf
      uses: actions/checkout@v2
      with:
        repository: asdf-vm/asdf
        path: asdf
    - name: Run tests
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        . asdf/asdf.sh
        asdf plugin-test java "$GITHUB_WORKSPACE" --asdf-plugin-gitref "$GITHUB_SHA" --asdf-tool-version adoptopenjdk-8.0.252+9.1.openj9-0.20.0 java -version
    - name: macOS Check java_home integration
      if: matrix.os == 'macOS-latest'
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export ASDF_CONFIG_FILE=${HOME}"/.asdfrc"
        echo "java_macos_integration_enable = yes" > "${ASDF_CONFIG_FILE}"
        . asdf/asdf.sh
        asdf plugin-test java "$GITHUB_WORKSPACE" --asdf-plugin-gitref "$GITHUB_SHA" --asdf-tool-version zulu-8.52.0.23 /usr/libexec/java_home -V 2>&1 | grep "Zulu 8.52.0.23"
    - name: Setup JAVA_HOME setting
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export ASDF_CONFIG_FILE=${HOME}"/.asdfrc"
        echo "java_macos_integration_enable = yes" > "${ASDF_CONFIG_FILE}"
        . asdf/asdf.sh
        asdf plugin add java "$GITHUB_WORKSPACE"
        asdf install java adoptopenjdk-8.0.252+9.1.openj9-0.20.0
        asdf global java adoptopenjdk-8.0.252+9.1.openj9-0.20.0
        echo ". $PWD/asdf/asdf.sh" >> $HOME/.zshrc
        echo ". $HOME/.asdf/plugins/java/set-java-home.zsh" >> $HOME/.zshrc
        echo "source-bash $PWD/asdf/asdf.sh" >> $HOME/.xonshrc
        echo "source $HOME/.asdf/plugins/java/set-java-home.xsh" >> $HOME/.xonshrc
        mkdir -p $HOME/.config/fish/functions/
        ln -s $HOME/.asdf/plugins/java/set-java-home.fish $HOME/.config/fish/functions/asdf_update_java_home.fish
        echo "source $PWD/asdf/asdf.fish" >> $HOME/.config/fish/config.fish
        echo "asdf_update_java_home" >> $HOME/.config/fish/config.fish
    - name: Run JAVA_HOME setting test fish
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $JAVA_HOME | grep adoptopenjdk-8.0.252+9.1.openj9-0.20.0
      shell: fish {0}
    - name: Run JAVA_HOME setting test bash
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        . asdf/asdf.sh
        . set-java-home.bash
        _asdf_java_prompt_command
        echo $JAVA_HOME | grep adoptopenjdk-8.0.252+9.1.openj9-0.20.0
      shell: bash {0}
    - name: Run JAVA_HOME setting test xonsh
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $JAVA_HOME
        source $HOME/.xonshrc
        echo $JAVA_HOME
        echo $JAVA_HOME | grep adoptopenjdk-8.0.252+9.1.openj9-0.20.0
      shell: xonsh {0}
    - name: Run JAVA_HOME setting test zsh
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        source $HOME/.zshrc
        asdf_update_java_home
        echo $JAVA_HOME | grep adoptopenjdk-8.0.252+9.1.openj9-0.20.0
      shell: zsh {0}
    - name: Setup system tool-version test on macOS
      if: matrix.os == 'macOS-latest'
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export ASDF_CONFIG_FILE=${HOME}"/.asdfrc"
        echo "java_macos_integration_enable = yes" > "${ASDF_CONFIG_FILE}"
        . asdf/asdf.sh
        . set-java-home.bash
        asdf install java zulu-16.28.11
        mkdir system
        cd system
        echo "java system" > .tool-versions
    - name: Run system tool-version test on macOS with fish
      if: matrix.os == 'macOS-latest'
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $JAVA_HOME
        cd system
        asdf_update_java_home
        echo $JAVA_HOME
      shell: fish {0}
    - name: Run system tool-version test on macOS with bash
      if: matrix.os == 'macOS-latest'
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $JAVA_HOME
        declare -F
        alias
        alias -p
        echo $PATH
        . asdf/asdf.sh
        . set-java-home.bash
        cd system
        asdf which java
        _asdf_java_prompt_command
        asdf which java
        echo $JAVA_HOME
      shell: bash {0}
    - name: Run system tool-version test on macOS with xonsh
      if: matrix.os == 'macOS-latest'
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $JAVA_HOME
        cd system
        asdf which java
        echo $JAVA_HOME
      shell: xonsh {0}
    - name: Run system tool-version test on macOS with zsh
      if: matrix.os == 'macOS-latest'
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $JAVA_HOME
        source $HOME/.zshrc
        cd system
        asdf_update_java_home
        asdf which java
        echo $JAVA_HOME
      shell: zsh {0}
