name: asdf-java Tests
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macOS-latest']
    env:
      TERM: dumb
    steps:
    - uses: actions/checkout@v2
    - uses: mstksg/get-package@v1
      with:
        brew: bash coreutils jq shellcheck
        apt-get: jq shellcheck
    - name: Run ShellCheck
      run: |
        shellcheck -V
        shellcheck ./bin/functions
        shellcheck ./update_data.bash
    - name: Install asdf
      uses: actions/checkout@v2
      with:
        repository: asdf-vm/asdf
        path: asdf
    - name: Run tests
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        . asdf/asdf.sh
        asdf plugin-test java "$GITHUB_WORKSPACE" --asdf-plugin-gitref "$GITHUB_SHA" --asdf-tool-version adoptopenjdk-8.0.252+9.1.openj9-0.20.0 java -version
    - name: macOS Check java_home integration
      if: matrix.os == 'macOS-latest'
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export ASDF_CONFIG_FILE=${HOME}"/.asdfrc"
        echo "java_macos_integration_enable = yes" > "${ASDF_CONFIG_FILE}"
        . asdf/asdf.sh
        asdf plugin-test java "$GITHUB_WORKSPACE" --asdf-plugin-gitref "$GITHUB_SHA" --asdf-tool-version zulu-8.52.0.23 /usr/libexec/java_home -V 2>&1 | grep "Zulu 8.52.0.23"
    - name: Run JAVA_HOME setting tests ubuntu
      if: matrix.os == 'ubuntu-latest'
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        . asdf/asdf.sh
        asdf plugin add java
        asdf install java adoptopenjdk-8.0.252+9.1.openj9-0.20.0
        asdf global java adoptopenjdk-8.0.252+9.1.openj9-0.20.0
        sudo apt -qq install -y zsh fish xonsh bash
        echo ". ~/.asdf/plugins/java/set-java-home.bash" >> ~/.bashrc
        echo ". ~/.asdf/plugins/java/set-java-home.zsh" >> ~/.zshrc
        echo "source ~/.asdf/plugins/java/set-java-home.xsh" >> ~/.xonshrc
        mkdir -p ~/.config/fish/functions/
        ln -s ~/.asdf/plugins/java/set-java-home.fish ~/.config/fish/functions/asdf_update_java_home.fish
        echo "asdf_update_java_home" >> ~/.config/fish/config.fish
        unset JAVA_HOME; /usr/bin/fish
        echo $JAVA_HOME | grep adoptopenjdk-8.0.252+9.1.openj9-0.20.0
        exit $status
        unset JAVA_HOME; /usr/bin/bash
        echo $JAVA_HOME | grep adoptopenjdk-8.0.252+9.1.openj9-0.20.0
        exit $?
        unset JAVA_HOME; /usr/bin/xonsh
        echo $JAVA_HOME | grep adoptopenjdk-8.0.252+9.1.openj9-0.20.0
        exit _.rtn
        unset JAVA_HOME; /usr/bin/zsh
        echo $JAVA_HOME | grep adoptopenjdk-8.0.252+9.1.openj9-0.20.0
        exit $?
    - name: Run JAVA_HOME setting tests macOS
      if: matrix.os == 'macOS-latest'
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        . asdf/asdf.sh
        asdf plugin add java
        asdf install java adoptopenjdk-8.0.252+9.1.openj9-0.20.0
        asdf global java adoptopenjdk-8.0.252+9.1.openj9-0.20.0
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew install fish xonsh bash zsh
        echo ". ~/.asdf/plugins/java/set-java-home.bash" >> ~/.bashrc
        echo ". ~/.asdf/plugins/java/set-java-home.zsh" >> ~/.zshrc
        echo "source ~/.asdf/plugins/java/set-java-home.xsh" >> ~/.xonshrc
        mkdir -p ~/.config/fish/functions/
        ln -s ~/.asdf/plugins/java/set-java-home.fish ~/.config/fish/functions/asdf_update_java_home.fish
        echo "asdf_update_java_home" >> ~/.config/fish/config.fish
        unset JAVA_HOME; /usr/local/bin/fish
        echo $JAVA_HOME | grep adoptopenjdk-8.0.252+9.1.openj9-0.20.0
        exit $status
        unset JAVA_HOME; /usr/local/bin/bash
        echo $JAVA_HOME | grep adoptopenjdk-8.0.252+9.1.openj9-0.20.0
        exit $?
        unset JAVA_HOME; /usr/local/bin/xonsh
        echo $JAVA_HOME | grep adoptopenjdk-8.0.252+9.1.openj9-0.20.0
        exit _.rtn
        unset JAVA_HOME; /usr/local/bin/zsh
        echo $JAVA_HOME | grep adoptopenjdk-8.0.252+9.1.openj9-0.20.0
        exit $?

    - name: Run system tool-version test on macOS
      if: matrix.os == 'macOS-latest'
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export ASDF_CONFIG_FILE=${HOME}"/.asdfrc"
        echo "java_macos_integration_enable = yes" > "${ASDF_CONFIG_FILE}"
        . asdf/asdf.sh
        asdf plugin add java
        asdf install java zulu-8.52.0.23

        mkdir system
        cd system
        asdf local java system
        cd ..

        unset JAVA_HOME; /usr/local/bin/fish
        cd system
        java -version | grep "Zulu 8.52.0.23"
        exit $status
        unset JAVA_HOME; /usr/local/bin/bash
        cd system
        java -version | grep "Zulu 8.52.0.23"
        exit $?
        unset JAVA_HOME; /usr/local/bin/xonsh
        cd system
        java -version | grep "Zulu 8.52.0.23"
        exit _.rtn
        unset JAVA_HOME; /usr/local/bin/zsh
        cd system
        java -version | grep "Zulu 8.52.0.23"
        exit $?
